// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17dHo9-3skWPX6u5WFEWXvUk1Ad9SMZE',
    appId: '1:992749946878:web:7d6e5bc048c26da358e2af',
    messagingSenderId: '992749946878',
    projectId: 'moteregna-a44d2',
    authDomain: 'moteregna-a44d2.firebaseapp.com',
    storageBucket: 'moteregna-a44d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnAin8FBOph86_nWY2k9mYCbF2cMDfMw8',
    appId: '1:992749946878:android:764f7d562990915758e2af',
    messagingSenderId: '992749946878',
    projectId: 'moteregna-a44d2',
    storageBucket: 'moteregna-a44d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb7DfjvL4gwu2WPuDNyUelWv6CREl-Flw',
    appId: '1:992749946878:ios:6df6a8a59fd8fa8158e2af',
    messagingSenderId: '992749946878',
    projectId: 'moteregna-a44d2',
    storageBucket: 'moteregna-a44d2.firebasestorage.app',
    iosBundleId: 'com.moteregna.customer.moteregnaCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb7DfjvL4gwu2WPuDNyUelWv6CREl-Flw',
    appId: '1:992749946878:ios:6df6a8a59fd8fa8158e2af',
    messagingSenderId: '992749946878',
    projectId: 'moteregna-a44d2',
    storageBucket: 'moteregna-a44d2.firebasestorage.app',
    iosBundleId: 'com.moteregna.customer.moteregnaCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD17dHo9-3skWPX6u5WFEWXvUk1Ad9SMZE',
    appId: '1:992749946878:web:3dbe9983ebfd167a58e2af',
    messagingSenderId: '992749946878',
    projectId: 'moteregna-a44d2',
    authDomain: 'moteregna-a44d2.firebaseapp.com',
    storageBucket: 'moteregna-a44d2.firebasestorage.app',
  );

}